# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1caccUTzn73DzLpajHfVZyIJgIfHh9gcP
"""

# earthquake_analysis.py

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


url = "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/significant_month.csv"
df = pd.read_csv(url)


print("Dataset shape:", df.shape)
print(df.columns)


df['time'] = pd.to_datetime(df['time'])


top_10 = df.sort_values('mag', ascending=False).head(10)
print("\nTop 10 strongest earthquakes:\n", top_10[['place', 'mag', 'time']])


plt.figure(figsize=(10, 6))
plt.barh(top_10['place'], top_10['mag'], color='red')
plt.xlabel("Magnitude")
plt.title("Top 10 Strongest Earthquakes (Past 30 Days)")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()


plt.figure(figsize=(8, 5))
plt.hist(df['mag'], bins=10, color='orange', edgecolor='black')
plt.title("Distribution of Earthquake Magnitudes")
plt.xlabel("Magnitude")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 5))
plt.plot(df['time'], df['mag'], marker='o', linestyle='-', color='purple')
plt.title("Earthquake Magnitudes Over Time")
plt.xlabel("Date")
plt.ylabel("Magnitude")
plt.tight_layout()
plt.show()


avg_mag_by_type = df.groupby('type')['mag'].mean().sort_values(ascending=False)

plt.figure(figsize=(6, 4))
avg_mag_by_type.plot(kind='bar', color='green')
plt.title("Average Magnitude by Earthquake Type")
plt.ylabel("Average Magnitude")
plt.tight_layout()
plt.show()

